import type { Category } from "./categories";

/**
 * Contemporary Kurdish figures — verified, notable people only.
 * Every hint states clearly WHAT the person is known for (role, achievement, dates).
 */
export const kurdishModernCategory: Category = {
  id: "modern",
  title: "کەسایەتییە هاوچەرخەکانی کورد",
  subtitle: "سیاسەتمەدار، هونەرمەند، نووسەر، یاریزان و ڕۆژنامەنووسانی ئەمڕۆ",
  emoji: "⭐",
  gradient: "from-emerald-500 via-green-600 to-teal-700",
  accent: "bg-emerald-400",
  cards: [
    /* ---------- Politics: Kurdistan Region of Iraq ---------- */
    { name: "مەسعود بارزانی", latin: "Masoud Barzani", hint: "سەرۆکی پارتی دیموکراتی کوردستان؛ سەرۆکی هەرێمی کوردستان ٢٠٠٥–٢٠١٧؛ کوڕی مەلا مستەفا بارزانی؛ ڕیفراندۆمی سەربەخۆیی ٢٠١٧ی ئەنجام دا", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Masoud_Barzani_2017.jpg/440px-Masoud_Barzani_2017.jpg" },
    { name: "مام جەلال", latin: "Jalal Talabani", hint: "دامەزرێنەری یەکێتیی نیشتمانیی کوردستان؛ یەکەم سەرۆکی کوردی عێراق (٢٠–٢٠٤)", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Jalal_Talabani_wef_2008.jpg/440px-Jalal_Talabani_wef_2008.jpg" },
    { name: "نێچیرڤان بارزانی", latin: "Nechirvan Barzani", hint: "سەرۆکی هەرێمی کوردستان لە ٢٠١٩ەوە؛ پێشتر سەرۆک وەزیران؛ کوڕی ئیدریس بارزانی و برازای مەسعود", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nechirvan_Barzani_2023.jpg/440px-Nechirvan_Barzani_2023.jpg" },
    { name: "مەسرور بارزانی", latin: "Masrour Barzani", hint: "سەرۆک وەزیرانی هەرێمی کوردستان لە ٢٠١٩ەوە؛ پێشتر سەرۆکی ئەنجومەنی ئاسایشی هەرێم؛ کوڕی مەسعود بارزانی", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Masrour_Barzani_Munich_2020.jpg/440px-Masrour_Barzani_Munich_2020.jpg" },
    { name: "بافڵ تاڵەبانی", latin: "Bafel Talabani", hint: "سەرۆکی یەکێتیی نیشتمانیی کوردستان لە ٢٠٢١ەوە؛ کوڕی گەورەی مام جەلال و هێرۆ خان", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Bafel_Talabani.jpg/440px-Bafel_Talabani.jpg" },
    { name: "قوباد تاڵەبانی", latin: "Qubad Talabani", hint: "جێگری سەرۆک وەزیرانی هەرێمی کوردستان؛ کوڕی بچووکی مام جەلال؛ پێشتر نوێنەری هەرێم لە واشنتن", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Qubad_Talabani_2017.jpg/440px-Qubad_Talabani_2017.jpg" },
    { name: "نەوشیروان مستەفا", latin: "Nawshirwan Mustafa", hint: "دامەزرێنەری بزووتنەوەی گۆڕان ٢٠٠؛ پێشتر جێگری سکرتێری یەکێتی؛ مێژوونووس و نووسەر", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Nawshirwan_Mustafa.jpg/440px-Nawshirwan_Mustafa.jpg" },
    { name: "بەرهەم ساڵح", latin: "Barham Salih", hint: "سەرۆک کۆماری عێراق ٢٠١٨–٢٠٢٢؛ سەرۆک وەزیرانی پێشووی هەرێم؛ دامەزرێنەری زانکۆی ئەمریکی سلێمانی", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Barham_Salih_2019.jpg/440px-Barham_Salih_2019.jpg" },
    { name: "فوئاد مەعسوم", latin: "Fuad Masum", hint: "سەرۆکی پێشووی عێراق (٢٠١٤–٢٠٨)؛ یەکێک لە دامەزرێنەرانی یەکێتی", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Fuad_Masum_2014.jpg/440px-Fuad_Masum_2014.jpg" },
    { name: "لەتیف ڕەشید", latin: "Abdul Latif Rashid", hint: "سەرۆک کۆماری عێراق ٢٠٢٢–٢٠٢٦؛ ئەندازیاری ئاو و وەزیری پێشووی سەرچاوەکانی ئاوی عێراق", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Abdul_Latif_Rashid.jpg/440px-Abdul_Latif_Rashid.jpg" },
    { name: "نزار ئامێدی", latin: "Nizar Amidi", hint: "سەرۆکی عێراق لە ٢٠٢٦ەوە؛ ئەندامی یەکێتیی نیشتمانی", difficulty: "medium" },
    { name: "هۆشیار زێباری", latin: "Hoshyar Zebari", hint: "وەزیری دەرەوەی عێراق ٢٠٠٣–٢٠١٤ و وەزیری دارایی؛ لە سەرکردایەتیی پارتی؛ مامی نێچیرڤان بارزانی", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Hoshyar_Zebari_2012.jpg/440px-Hoshyar_Zebari_2012.jpg" },
    { name: "کۆسرەت ڕەسوڵ", latin: "Kosrat Rasul", hint: "فەرماندەی ناودار پێشمەرگە؛ دووەم سەرۆک وەزیرانی هەرێمی کوردستان ١٩٩٣–٢٠٠١؛ جێگری سەرۆکی هەرێم ٢٠٠٥–٢٠١٧؛ سەرۆکی ئەنجومەنی باڵای سیاسیی یەکێتی", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Kosrat_Rasul_Ali.jpg/440px-Kosrat_Rasul_Ali.jpg" },
    { name: "هێرۆ ئیبراهیم ئەحمەد", latin: "Hero Ibrahim Ahmad", hint: "خاتوونی یەکەمی عێراق ٢٠٠٥–٢٠١٤؛ هاوسەری مام جەلال؛ کچی نووسەر ئیبراهیم ئەحمەد؛ دامەزرێنەری کەناڵی کوردسات", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Hero_Ibrahim_Ahmad.jpg/440px-Hero_Ibrahim_Ahmad.jpg" },
    { name: "شاناز ئیبراهیم ئەحمەد", latin: "Shanaz Ibrahim Ahmad", hint: "خاتوونی یەکەمی عێراق ٢٠٢٢–٢٠٢٦؛ هاوسەری لەتیف ڕەشید؛ کچی نووسەر ئیبراهیم ئەحمەد و خوشکی هێرۆ", difficulty: "hard" },
    { name: "سامی عەبدولڕەحمان", latin: "Sami Abdulrahman", hint: "جێگری سەرۆک وەزیرانی هەرێم لە ١٩٩٩ەوە؛ لە تەقینەوەی جەژنی هەولێر ١ی شوباتی ٢٠٠٤ لەگەڵ کوڕەکەی شەهید بوو؛ گەورەترین پارکی هەولێر بە ناویەوەیە", difficulty: "medium" },
    { name: "فرانسۆ حەریری", latin: "Franso Hariri", hint: "سیاسەتمەداری ئاشووریی ئەندامی پارتی؛ پارێزگاری هەولێر ١٩٩٦–٢٠٠١؛ لە ١٨ی شوباتی ٢٠٠١ تیرۆرکرا؛ یاریگای فرانسۆ حەریری بە ناویەوەیە", difficulty: "medium" },
    { name: "ڕۆژ نوری شاوەیس", latin: "Roj Nuri Shawais", hint: "دووەم سەرۆکی پەرلەمانی کوردستان؛ جێگری سەرۆک وەزیرانی عێراق چەند خولێک", difficulty: "medium" },
    { name: "جەوهەر نامق سالم", latin: "Jawhar Namiq Salim", hint: "یەکەم سەرۆکی پەرلەمانی کوردستان؛ پێشمەرگە و سکرتێری پێشووی مەکتەبی سیاسی پارتی١", difficulty: "hard" },
    { name: "عەدنان موفتی", latin: "Adnan Mufti", hint: "سەرۆکی پەرلەمانی کوردستان ٢٠٠٥–٢٠٠٩؛ ئەندامی مەکتەبی سیاسیی یەکێتی؛ وەزیری پێشووی ڕۆشنبیری", difficulty: "hard" },
    { name: "فازڵ میرانی", latin: "Fazil Mirani", hint: "سکرتێری مەکتەبی سیاسیی پارتی دیموکراتی کوردستان بۆ ماوەیەکی درێژ", difficulty: "hard" },
    { name: "کەریم سنجاری", latin: "Karim Sinjari", hint: "وەزیری ناوخۆی هەرێم بۆ چوار کابینە؛ ئەندامی مەکتەبی سیاسی پارتی", difficulty: "hard" },
    { name: "ڕێبوار ئەحمەد", latin: "Rebar Ahmed", hint: "وەزیری ناوخۆی هەرێمی کوردستان لە کابینەی نۆیەم؛ کاندیدی پێشووی سەرۆک کۆماری عێراق لەلایەن پارتییەوە", difficulty: "medium" },
    { name: "هێمن هەورامی", latin: "Hemin Hawrami", hint: "جێگری سەرۆکی پەرلەمانی کوردستان لە شوباتی ٢٠١٩ەوە؛ بەرپرسی پێشووی پەیوەندییە دەرەوەکانی پارتی؛ خاوەنی دکتۆرا و چەندین کتێبی سیاسی", difficulty: "hard" },
    { name: "کوێستان محەمەد", latin: "Kwestan Mohammed", hint: "پەرلەمانتار و وەزیری پێشووی کاروباری کۆمەڵایەتی؛ لە ڕیزەکانی گۆڕان", difficulty: "hard" },
    { name: "نەجمەدین کەریم", latin: "Najmaldin Karim", hint: "پارێزگاری پێشووی کەرکووک؛ نەشتەرگەری دەمار لە ئەمریکا", difficulty: "medium" },
    { name: "خالد شوانی", latin: "Khalid Shwani", hint: "پارێزگاری کەرکووک لە ٢٠٢٤ەوە؛ پێشتر وەزیری داد لە حکومەتی عێراق و وتەبێژی سەرۆکایەتی کۆمار", difficulty: "hard" },
    { name: "ئومێد خۆشناو", latin: "Omed Khoshnaw", hint: "پارێزگاری هەولێر؛ لە شوباتی ٢٠٢١ سوێندی یاسایی خوارد؛ پێشتر سەرۆکی فراکسیۆنی پارتی لە پەرلەمانی کوردستان", difficulty: "hard" },
    { name: "هەڤاڵ ئەبوبەکر", latin: "Haval Abubakir", hint: "پارێزگاری سلێمانی؛ مامۆستای پێشووی زانکۆی سلێمانی و نووسەر لە بزووتنەوەی گۆڕان", difficulty: "hard" },
    { name: "ئازاد بەرزنجی", latin: "Azad Barzinji", hint: "وەرگێڕ و ڕۆشنبیری ناوداری کورد لە سلێمانی؛ زیاتر لە ٣٥ کتێبی فەلسەفە و ئەدەبی جیهانیی وەرگێڕاوەتە سەر کوردی", difficulty: "hard" },
    { name: "جەبار یاوەر", latin: "Jabbar Yawar", hint: "سکرتێری گشتیی پێشووی وەزارەتی پێشمەرگە بۆ ١٧ ساڵ و وتەبێژی ناسراوی هێزەکان؛ ئێستا شارەزای کاروباری ئاسایشە", difficulty: "hard" },
    { name: "مەلا بەختیار", latin: "Mala Bakhtiar", hint: "ناوی ڕاستەقینەی حیکمەت محەمەد کەریم؛ هاوسەرۆکی ئەنجومەنی باڵای سیاسیی یەکێتی لەگەڵ کۆسرەت ڕەسوڵ؛ فەرماندەی پێشمەرگە؛ نووسەر و شیکەرەوەی سیاسی", difficulty: "medium" },
    { name: "سەعدی ئەحمەد پیرە", latin: "Saadi Ahmad Pira", hint: "وتەبێژی مەکتەبی سیاسیی یەکێتیی نیشتمانیی کوردستان؛ ئەندامی کۆنی سەرکردایەتیی یەکێتی", difficulty: "hard" },
    { name: "مەحمود سەنگاوی", latin: "Mahmud Sangawi", hint: "فەرماندەی دێرینی پێشمەرگە و سەرکردەی یەکێتی؛ بەرپرسی میحوەری گەرمەسێر لە شەڕی دژ بە داعش", difficulty: "hard" },
    { name: "ئاراس شێخ جەنگی", latin: "Aras Sheikh Jangi", hint: "کوڕەزای مام جەلال؛ لە دامەزرێنەرانی بەرەی گەل؛ بەرپرسی پێشووی دەزگای زانیاری", difficulty: "medium" },
    { name: "لاهور شێخ جەنگی", latin: "Lahur Sheikh Jangi", hint: "سەرۆکی بەرەی گەل و هاوسەرۆکی پێشووی یەکێتی؛ سەرۆکی پێشووی دەزگای پاراستن؛ لە ٢٢ی ئابی ٢٠٢٥ دوای شەڕی هوتێلی لالەزار لە سلێمانی دەستگیرکرا", difficulty: "medium" },
    { name: "شاسوار عەبدولواحید", latin: "Shaswar Abdulwahid", hint: "بازرگان و خاوەنی تۆڕی میدیایی NRT؛ دامەزرێنەری بزووتنەوەی نەوەی نوێ لە ٢٠١٧؛ لە ئابی ٢٠٢٥ دەستگیرکرا و بە پێنج مانگ زیندان حوکم درا", difficulty: "medium" },
    { name: "سروە عەبدولواحید", latin: "Srwa Abdulwahid", hint: "سەرۆکی فراکسیۆنی نەوەی نوێ لە پەرلەمانی عێراق لە بەغدا؛ خوشکی شاسوار عەبدولواحید", difficulty: "medium" },
    { name: "عەلی باپیر", latin: "Ali Bapir", hint: "دامەزرێنەر و سەرۆکی کۆمەڵی نیشتمانیی کوردستان (کۆمەڵ) لە ٢٠٠١؛ مامۆستای ئایینی و نووسەر؛ ٢٠٠٣–٢٠٠٥ لەلایەن هێزەکانی ئەمریکا دەستبەسەرکرا", difficulty: "medium" },
    { name: "سەڵاحەدین بەهائەدین", latin: "Salahaddin Bahaaeddin", hint: "لە دامەزرێنەرانی یەکگرتووی ئیسلامیی کوردستان لە ٦ی شوباتی ١٩٩٤؛ سکرتێری گشتیی یەکگرتوو بۆ زیاتر لە ٢٦ ساڵ", difficulty: "medium" },
    { name: "محەمەد حاجی مەحمود", latin: "Muhammad Haji Mahmud", hint: "سکرتێری حیزبی سۆسیالیست دیموکراتی کوردستان؛ فەرماندەی پێشمەرگە، نازناوی کاک محەمەد", difficulty: "medium" },
    { name: "سیروان بارزانی", latin: "Sirwan Barzani", hint: "فەرماندەی پێشمەرگە لە بەرەی گوێر دژی داعش؛ دامەزرێنەری کۆمپانیای کۆرەک تێلێکۆم", difficulty: "medium" },
    { name: "مەنسوور بارزانی", latin: "Mansour Barzani", hint: "فەرماندەی لەشکری تایبەتی پێشمەرگە (گولان)؛ کوڕی مەسعود بارزانی؛ فەرماندەی شەڕەکانی دژی داعش", difficulty: "medium" },
    { name: "کەمال کەرکووکی", latin: "Kamal Kirkuki", hint: "سەرۆکی پەرلەمانی کوردستان ٢٠٠٩–٢٠١٢؛ ناوی ڕاستەقینەی محەمەد قادر عەبدوڵڵا؛ لە ١٤ ساڵیدا بوو بە پێشمەرگە؛ فەرماندەی پێشمەرگە دژی داعش لە کەرکووک", difficulty: "hard" },
    { name: "ڤیان دەخیل", latin: "Vian Dakhil", hint: "پەرلەمانتاری ئێزیدی لە پەرلەمانی عێراق؛ لە ئابی ٢٠١٤ بە قسە گریانەکەی لە پەرلەمان جیهانی ئاگادار کردەوە لە کارەساتی شەنگال", difficulty: "medium" },
    { name: "نادیە موراد", latin: "Nadia Murad", hint: "چالاکوانی ئێزیدی؛ خەڵاتی نۆبڵی ئاشتی ٢٠١٨ی لەگەڵ دێنی موکوێگێ بردەوە بۆ خەبات دژی توندوتیژیی سێکسی وەک چەکی جەنگ؛ کتێبی دوایین کچ", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Nadia_Murad_Basecamp_2018.jpg/440px-Nadia_Murad_Basecamp_2018.jpg" },
    { name: "تەحسین سەعید بەگ", latin: "Tahsin Said Beg", hint: "میری ئێزیدییەکانی جیهان لە ١٩٤٤ەوە تا ٢٠١٩؛ لە ١١ ساڵیدا بوو بە میر؛ سەرۆکی ئەنجومەنی ڕۆحانیی ئێزیدییان", difficulty: "hard" },

    /* ---------- Politics: Bakur (Turkey) ---------- */
    { name: "عەبدوڵڵا ئۆجەلان", latin: "Abdullah Öcalan", hint: "دامەزرێنەری پەکەکە ١٩٧٨؛ لە ١٩٩٩ لە کینیا دەستگیرکرا و لە دوورگەی ئیمراڵی زیندانییە", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Abdullah_%C3%96calan.jpg/440px-Abdullah_%C3%96calan.jpg" },
    { name: "سەلاحەدین دەمیرتاش", latin: "Selahattin Demirtaş", hint: "هاوسەرۆکی پێشووی هەدەپە و کاندیدی سەرۆکایەتیی تورکیا؛ پارێزەر و نووسەر؛ لە ٢٠١٦ەوە زیندانی کرا و لە ئایاری ٢٠٢٤ لە دادگای کۆبانێ بە ٤٢ ساڵ زیندان حوکم درا", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Selahattin_Demirta%C5%9F.jpg/440px-Selahattin_Demirta%C5%9F.jpg" },
    { name: "لەیلا زانا", latin: "Leyla Zana", hint: "یەکەم ژنی کورد لە پەرلەمانی تورکیا ١٩٩١؛ بۆ سوێندخواردن بە کوردی زیندانی کرا؛ خەڵاتی ساخارۆڤ ١٩٩٥", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Leyla_Zana_2008.jpg/440px-Leyla_Zana_2008.jpg" },
    { name: "ئەحمەد تۆرک", latin: "Ahmet Türk", hint: "سیاسەتمەداری بەتەمەنی کورد؛ چەند جارێک شارەوانی ماردین بووە و هەر جارێک بە قەیوم لابراوە؛ لە دادگای کۆبانێ بە ١٠ ساڵ زیندان حوکم درا", difficulty: "hard" },
    { name: "عوسمان بایدەمیر", latin: "Osman Baydemir", hint: "شارەوانی ئامەد (دیاربەکر) ٢٠٠٤–٢٠١٤ و پەرلەمانتار؛ لە ٢٠١٨ ئەندامێتیی پەرلەمانی لێسەندرایەوە؛ ئێستا لە لەندەن لە تاراوگەیە", difficulty: "hard" },
    { name: "پەروین بولدان", latin: "Pervin Buldan", hint: "هاوسەرۆکی پێشووی هەدەپە؛ ئەندامی هەیئەتی دانوستانی ئاشتی لە تورکیا", difficulty: "hard" },
    { name: "میتهات سانجار", latin: "Mithat Sancar", hint: "هاوسەرۆکی پێشووی هەدەپە (٢٠٢٠–٢٠٢٣)؛ پرۆفیسۆری یاسای دەستووری لە زانکۆی ئەنقەرە", difficulty: "hard" },
    { name: "گولتان کشاناک", latin: "Gültan Kışanak", hint: "یەکەم ژن کە بووە هاوشارەوانی ئامەد؛ ڕۆژنامەنووس؛ لە ٢٠١٦ەوە زیندانی کرا و لە ئایاری ٢٠٢٤ ئازاد کرا", difficulty: "hard" },
    { name: "سەباحەت تونجەل", latin: "Sebahat Tuncel", hint: "پەرلەمانتار و هاوسەرۆکی پێشووی حیزبی دیموکراتیکی گەلان؛ چالاکوانی مافی ژنان؛ بە ١٢ ساڵ حوکم درا و لە ئایاری ٢٠٢٤ ئازاد کرا", difficulty: "hard" },
    { name: "فیگەن یوکسەکداغ", latin: "Figen Yüksekdağ", hint: "هاوسەرۆکی پێشووی هەدەپە شانبەشانی دەمیرتاش؛ لە ٢٠١٦ دەستگیرکرا و لە ٢٠٢٤ بە ٣٠ ساڵ زیندان حوکم درا", difficulty: "hard" },

    /* ---------- Politics: Rojava (Syria) ---------- */
    { name: "مەزڵوم عەبدی", latin: "Mazloum Abdi", hint: "فەرماندەی گشتیی هێزەکانی سوریای دیموکرات (SDF)؛ سەرکردەی شەڕی زەمینی دژی داعش لە کۆبانێ و ڕەققە", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Mazloum_Abdi.jpg/440px-Mazloum_Abdi.jpg" },
    { name: "ساڵح موسلیم", latin: "Salih Muslim", hint: "هاوسەرۆکی پێشووی پەیەدە لە ڕۆژئاڤا؛ ئەندازیاری کیمیا بە پیشە؛ دیپلۆماتی نێودەوڵەتیی کوردی ڕۆژئاڤا", difficulty: "hard", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Salih_Muslim_Muhammad.jpg/440px-Salih_Muslim_Muhammad.jpg" },
    { name: "ئیلهام ئەحمەد", latin: "Ilham Ahmed", hint: "سیاسەتمەداری ژن لە ڕۆژئاڤا؛ بەرپرسی پەیوەندییە دەرەوەکانی ئیدارەی خۆسەری باکوور و ڕۆژهەڵاتی سوریا", difficulty: "hard", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Ilham_Ehmed.jpg/440px-Ilham_Ehmed.jpg" },
    { name: "فۆزا یوسف", latin: "Foza Yusif", hint: "هاوسەرۆکی پێشووی پەیەدە؛ لە دامەزرێنەرانی سیستەمی ئیدارەی خۆسەری ڕۆژئاڤا", difficulty: "hard" },
    { name: "ئەلدار خەلیل", latin: "Aldar Khalil", hint: "یەکێک لە دامەزرێنەرانی TEV-DEM و سیستەمی ئیدارەی خۆسەر لە ڕۆژئاڤا", difficulty: "hard" },

    /* ---------- Politics: Rojhelat (Iran) ---------- */
    { name: "سادق شەرەفکەندی", latin: "Sadegh Sharafkandi", hint: "سکرتێری گشتیی حیزبی دیموکراتی کوردستانی ئێران دوای قاسملوو؛ لە ١٩٩٢ لە چێشتخانەی میکۆنۆسی بەرلین تیرۆرکرا", difficulty: "medium" },
    { name: "مستەفا هیجری", latin: "Mustafa Hijri", hint: "سکرتێری گشتیی حیزبی دیموکراتی کوردستانی ئێران لە ٢٠٠٤ەوە؛ خەباتکاری دێرینی ڕۆژهەڵات", difficulty: "hard" },
    { name: "عەبدوڵڵا موهتەدی", latin: "Abdullah Mohtadi", hint: "سکرتێری گشتیی کۆمەڵەی شۆڕشگێڕی زەحمەتکێشانی کوردستانی ئێران لە دامەزراندنیەوە لە ١٩٧٩", difficulty: "medium" },

    /* ---------- Music ---------- */
    { name: "شوان پەروەر", latin: "Şivan Perwer", hint: "ناوداترین گۆرانیبێژی کورمانجی؛ لە ١٩٧٦ەوە لە تاراوگە ژیا؛ گۆرانی کینێ ئەم و هەلەپچە", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Sivan_Perwer_2011.jpg/440px-Sivan_Perwer_2011.jpg" },
    { name: "ئەحمەد کایا", latin: "Ahmet Kaya", hint: "گۆرانیبێژی کوردی تورکیا؛ دوای ڕاگەیاندنی کوردایەتی لە ١٩٩ چووە تاراوگە", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Ahmet_Kaya.jpg/440px-Ahmet_Kaya.jpg" },
    { name: "ناسر ڕەزازی", latin: "Nasser Razazi", hint: "گۆرانیبێژی شۆڕشگێڕی ڕۆژهەڵات لە سنە؛ دەیان گۆرانی نیشتمانی تۆمار کردووە", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Naser_Razazi.jpg/440px-Naser_Razazi.jpg" },
    { name: "مەزهەر خالقی", latin: "Mazhar Khaleqi", hint: "گۆرانیبێژی گەورەی کورد لە سنە؛ زیاتر لە ١٥٠ پارچە مۆسیقای فۆلکلۆری کوردی تۆمار کردووە", difficulty: "medium" },
    { name: "زەکەریا عەبدوڵڵا", latin: "Zakaria Abdulla", hint: "گۆرانیبێژی کورد لە هەولێر؛ چەندین ئەلبومی پۆپی کوردی بڵاوکردووەتەوە", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Zakaria_Abdulla.jpg/440px-Zakaria_Abdulla.jpg" },
    { name: "عەدنان کەرەم", latin: "Adnan Karim", hint: "گۆرانیبێژی سلێمانی و وێنەکێش؛ شیعرەکانی نالی، مەحوی و پیرەمێرد بە مەقامی کوردی دەڵێتەوە", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Adnan_Karim.jpg/440px-Adnan_Karim.jpg" },
    { name: "چۆپی فەتاح", latin: "Chopy Fatah", hint: "گۆرانیبێژی ژنی کورد لە کەرکووک؛ لە ناسراوترین دەنگە ژنانەکانی پۆپی کوردی", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Chopy_Fatah.jpg/440px-Chopy_Fatah.jpg" },
    { name: "هەڵکەوت زاهیر", latin: "Halkawt Zaher", hint: "ئاوازدانەر و ژەنیاری ئۆبۆی سلێمانی؛ یەکێک لە بەرهەمهێنەرترین ئاوازدانەرانی مۆسیقای کوردی", difficulty: "medium" },
    { name: "دەشنێ موراد", latin: "Dashni Morad", hint: "گۆرانیبێژی پۆپ و پێشکەشکاری تەلەفزیۆن؛ لە هۆڵەندا گەورە بووە؛ چالاکوانی مافی ژنان و ژینگە", difficulty: "medium" },
    { name: "دیار دەرسیم", latin: "Diyar Dersim", hint: "گۆرانیبێژی شۆڕشگێڕی کورد لە باکووری کوردستان، خەڵکی دەرسیم؛ بە کورمانجی و زازاکی دەیان ئەلبومی بڵاوکردووەتەوە لە ١٩٨٨ەوە", difficulty: "medium" },
    { name: "ڕۆژین", latin: "Rojin", hint: "گۆرانیبێژ و ئەکتەری ژنی کورد لە باکوور؛ پێشکەشکاری بەرنامەی کوردی لە کەناڵی TRT بوو", difficulty: "medium" },
    { name: "ئاینور دۆغان", latin: "Aynur Doğan", hint: "گۆرانیبێژی ژنی کورد لە دەرسیم؛ گۆرانی کەچە کوردان؛ لە فیستیڤاڵە جیهانییەکان بەشداری کردووە", difficulty: "medium" },
    { name: "جوان حاجۆ", latin: "Ciwan Haco", hint: "گۆرانیبێژی کورد؛ یەکەم کەس بوو ڕۆک و جاز و پۆپی تێکەڵ بە مۆسیقای کوردی کرد", difficulty: "medium" },
    { name: "مەم ئارارات", latin: "Mem Ararat", hint: "گۆرانیبێژ و ئاوازدانەری کورمانجی لە ماردین؛ ئەلبومی قولینگ و نیشتمان؛ چەند کۆنسێرتێکی لە تورکیا قەدەغە کران", difficulty: "medium" },
    { name: "نیزامەدین ئاریچ", latin: "Nizamettin Ariç", hint: "گۆرانیبێژ و دەرهێنەری کورد؛ دەرهێنەر و ئەکتەری سەرەکیی فیلمی «کلامێک بۆ بێکۆ» (١٩٩٢)، یەکەم فیلمی درێژی کوردی؛ لە ١٩٨١ەوە لە بەرلین دەژی", difficulty: "hard" },
    { name: "ئارام تیگران", latin: "Aram Tigran", hint: "گۆرانیبێژی ئەرمەنی کە بە کوردی گۆرانیی دەگوت؛ دەنگێکی خۆشەویست لای کوردان", difficulty: "hard" },
    { name: "شەهرام نازری", latin: "Shahram Nazeri", hint: "گۆرانیبێژی کورد لە کرماشان؛ بە شیعری ڕۆمی و مۆسیقای کلاسیکی ئێرانی جیهانی ناسراوە", difficulty: "medium" },
    { name: "کەیهان کەلهوڕ", latin: "Kayhan Kalhor", hint: "ژەنیاری کەمانچەی کورد؛ لە ٢٠١٧ لەگەڵ گرووپی ڕێگای ئاوریشمی یۆ یۆ ما خەڵاتی گرامیی بردەوە بۆ ئەلبومی Sing Me Home", difficulty: "hard" },
    { name: "کامکاران", latin: "Kamkars", hint: "گرووپی مۆسیقای بنەماڵەیی کورد لە سنە؛ پێکهاتووە لە خوشک و برایان؛ ناسراو لە ئاستی جیهان", difficulty: "medium" },
    { name: "هێڵی لوڤ", latin: "Helly Luv", hint: "گۆرانیبێژی پۆپی کورد؛ کلیپی ڕیسک ئیت ئۆڵ و ڕیڤۆلوشن لە بەرەکانی شەڕی داعش تۆمار کرد", difficulty: "hard" },
    { name: "شەهرام نیازەد", latin: "Shahram Niyazade", hint: "گۆرانیبێژی پۆپی کورد لە هەولێر؛ گۆرانییەکانی «چیرۆکی خۆش» و «گەشتی هاوار»", difficulty: "medium" },
    { name: "هۆزان دیار", latin: "Hozan Diyar", hint: "گۆرانیبێژی فۆلک و پۆپی کورد؛ گۆرانییەکانی وڵات، کۆرکۆ دینۆ و لێرخە لۆڕی", difficulty: "medium" },
    { name: "کاروان کامیل", latin: "Karwan Kamil", hint: "گۆرانیبێژی کورد لە دهۆک؛ گۆرتنی بیناز لەگەڵ دەشنێ موراد یەکەم گۆرانی کوردی بوو کە ملیۆنەها بینەری لە یوتیوب بەدەستهێنا", difficulty: "medium" },
    { name: "سەڕهادو", latin: "Serhado", hint: "ڕاپەری کورد لە سوید؛ یەکەم ڕاپەری کوردی بە زمانی کوردی؛ گۆرانییەکانی لو دیلۆ و زمانە کوردی", difficulty: "medium" },
    { name: "ڕیزان سەعید", latin: "Rizan Said", hint: "ئاوازدانەر و بەرهەمهێنەری سوری لە ڕەس ئەلعین؛ ئاوازی دەیان گۆرانی و بەرهەمە تەلەفزیۆنی سوری؛ سولو ئەلبومی «پاشای کێبۆرد»", difficulty: "hard" },

    /* ---------- Literature ---------- */
    { name: "شێرکۆ بێکەس", latin: "Sherko Bekas", hint: "گەورەترین شاعیری نوێخوازی کورد (١٩٤٠–٢٠١٣)؛ کوڕی فایەق بێکەس؛ ڕەوتی ڕوانگەی دامەزراند؛ لە ١٩٨٧ خەڵاتی توخۆلسکیی سوید و ئازادیی فلۆرێنسای بردەوە", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sherko_Bekas.jpg/440px-Sherko_Bekas.jpg" },
    { name: "بەختیار عەلی", latin: "Bachtyar Ali", hint: "نووسەری ڕۆمانی کورد؛ ئێوارەی پەروانە و دوا هەناری دنیا؛ لە ئەڵمانیا دەژی؛ یەکەم نووسەری نا-ئەوروپی بوو خەڵاتی نێلی زاکسی بردەوە (٢٠١٧)", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Bachtyar_Ali_2017.jpg/440px-Bachtyar_Ali_2017.jpg" },
    { name: "عەبدوڵڵا پەشێو", latin: "Abdulla Pashew", hint: "شاعیری خۆشەویستی کورد؛ شیعرەکانی بۆ چەند زمانێک وەرگێڕدراون", difficulty: "medium" },
    { name: "لەتیف هەڵمەت", latin: "Latif Halmat", hint: "شاعیری نوێخوازی کورد لە کەرکووک؛ یەکێک لە دەنگە سەرەکییەکانی شیعری نوێی کوردی", difficulty: "medium" },
    { name: "ڕەفیق سابیر", latin: "Rafiq Sabir", hint: "شاعیر، بیرمەند و وەرگێڕی کورد؛ دوکتۆرا لە فەلسەفە لە سوید؛ خاوەنی چەندین دیوانی شیعری مۆدێرن و لێکۆڵینەوەی ڕەخنەیی", difficulty: "hard" },
    { name: "فەرهاد پیرباڵ", latin: "Farhad Pirbal", hint: "نووسەر، شاعیر و وێنەکێش؛ مامۆستای زانکۆی سەڵاحەدین؛ دکتۆرا لە ئەدەبی کوردی لە سۆربۆنی پاریس", difficulty: "hard" },
    { name: "شێرزاد حەسەن", latin: "Sherzad Hassan", hint: "ڕۆماننووسی کورد؛ ڕۆمانی «حەسار و سەگەکانی باوکم» (١٩٩٦)؛ بە ڕەخنەگرتن لە کولتووری پیاوسالاری ناسراوە؛ لە فینلەندا دەژی", difficulty: "hard" },
    { name: "عەتا نەهایی", latin: "Ata Nahai", hint: "ڕۆماننووسی کورد لە بانە؛ ڕۆمانی گوڵی شۆڕان؛ لە ناوداری ڕۆمانی کوردی ڕۆژهەڵات", difficulty: "hard" },
    { name: "جان دۆست", latin: "Jan Dost", hint: "ڕۆماننووس و وەرگێڕی کورد لە کۆبانێ؛ ڕۆمانی «مێرنامە»؛ لە ئەڵمانیا دەژی", difficulty: "hard" },
    { name: "فرات جەوەری", latin: "Firat Cewerî", hint: "نووسەر و وەرگێڕی کورمانجی؛ گۆڤاری نودەمی دەرکرد؛ لە سوید دەژی", difficulty: "hard" },
    { name: "حەلیم یووسڤ", latin: "Helîm Yûsiv", hint: "ڕۆماننووسی کورمانجی لە ڕۆژئاڤا؛ پارێزەر بە پیشە؛ لە ئەڵمانیا دەژی", difficulty: "hard" },
    { name: "سەلیم بەرەکات", latin: "Salim Barakat", hint: "شاعیر و ڕۆماننووسی کورد کە بە عەرەبی دەنووسێت؛ لە قامیشلۆ؛ لە گەورەترین نووسەرانی عەرەبیی هاوچەرخ", difficulty: "hard" },
    { name: "چۆمان هەردی", latin: "Choman Hardi", hint: "شاعیر و توێژەری کورد؛ دامەزرێنەری سەنتەری توێژینەوەی ڕەگەزی لە زانکۆی ئەمریکی سلێمانی؛ کتێبی لێکۆڵینەوە لەسەر ژنانی ڕزگاربووی ئەنفال", difficulty: "hard" },
    { name: "مەریوان وریا قانع", latin: "Mariwan Wrya Qani", hint: "نووسەر و بیرمەندی کورد؛ لێکۆڵینەوە لە فەلسەفە و کۆمەڵناسی؛ مامۆستای زانکۆ", difficulty: "hard" },
    { name: "فەرهاد شاکەلی", latin: "Farhad Shakely", hint: "شاعیر و توێژەری کورد لە زانکۆی ئوپسالای سوید؛ لێکۆڵینەوە لەسەر مەم و زینی ئەحمەدی خانی", difficulty: "hard" },

    /* ---------- Cinema ---------- */
    { name: "یەلماز گونەی", latin: "Yılmaz Güney", hint: "ئەکتەر و دەرهێنەری کورد لە تورکیا؛ فیلمی یۆل خەڵاتی «پاڵم دۆر»ی فیستیڤاڵی کانی ١٩٨٢ی بردەوە؛ لە زیندانەوە فیلمی ئاراستە دەکرد", difficulty: "medium", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Yilmaz_G%C3%BCney.jpg/440px-Yilmaz_G%C3%BCney.jpg" },
    { name: "بەهمەن قوبادی", latin: "Bahman Ghobadi", hint: "دەرهێنەری کورد لە بانە؛ کاتی ئەسپە سەرخۆشەکان و کیسەڵەکانیش دەفڕن؛ خەڵاتی کامێرا دۆری کان", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bahman_Ghobadi_2009.jpg/440px-Bahman_Ghobadi_2009.jpg" },
    { name: "هونەر سالیم", latin: "Hiner Saleem", hint: "دەرهێنەری کورد؛ فیلمی ڤۆدکا لیمۆن (خەڵاتی ڤینیس) و کیلۆمەتری سفر", difficulty: "medium" },
    { name: "شەوکەت ئەمین کورکی", latin: "Shawkat Amin Korki", hint: "دەرهێنەری کورد؛ فیلمی بەردی یادەوەری و کرۆسینگ دە داست؛ خەڵاتی چەند فیستیڤاڵێکی نێودەوڵەتی", difficulty: "hard" },
    { name: "جانۆ ڕۆژبیانی", latin: "Jano Rosebiani", hint: "دەرهێنەری کوردی دانیشتووی ئەمریکا؛ فیلمی ژیان (دەربارەی کیمیابارانی هەڵەبجە) و چاپلین لە باکوور", difficulty: "hard" },

    /* ---------- Journalism ---------- */
    { name: "ئاسۆس هەردی", latin: "Asos Hardi", hint: "ڕۆژنامەنووسی سەربەخۆ؛ دامەزرێنەری ڕۆژنامەی هاوڵاتی و ئاوێنە؛ کوڕی شاعیر ئەحمەد هەردی؛ خەڵاتی ئازادیی ڕۆژنامەگەری", difficulty: "medium" },
    { name: "سۆران مامە حەمە", latin: "Soran Mama Hama", hint: "ڕۆژنامەنووسی گەنجی گۆڤاری لڤین لە کەرکووک؛ دوای بڵاوکردنەوەی بابەت لەسەر گەندەڵی، لە تەمووزی ٢٠٠٨ لە تەمەنی ٢٣ ساڵیدا لەبەردەم ماڵەکەیان تیرۆرکرا", difficulty: "hard" },
    { name: "کاوە گەرمیانی", latin: "Kawa Garmiani", hint: "سەرنووسەری گۆڤاری ڕایەڵ و نووسەری ڕۆژنامەی ئاوێنە؛ بابەتی گەندەڵیی بڵاودەکردەوە؛ لە ٥ی کانوونی یەکەمی ٢٠١٣ لە کەلار تیرۆرکرا", difficulty: "hard" },

    /* ---------- Religious scholars ---------- */
    { name: "مەلا عەبدولکەریمی مودەڕیس", latin: "Abdulkarim Mudaris", hint: "زانا و مامۆستای گەورەی ئایینی کورد؛ موفتیی عێراق بوو؛ نزیکەی ١٥٠ بەرهەمی نووسیوە بە کوردی، عەرەبی و فارسی؛ تەفسیری نامی", difficulty: "hard" },
    { name: "شێخ نەهرۆ کەسنەزانی", latin: "Sheikh Nehro Kasnazani", hint: "ڕابەری ڕۆحیی تەریقەتی قادریی کەسنەزانی لە ٢٠٢٠ەوە دوای باوکی؛ گەورەترین تەریقەتی سۆفیی عێراق، خانەقای سەرەکی لە سلێمانی", difficulty: "hard" },

    /* ---------- Sport ---------- */
    { name: "نوری شاهین", latin: "Nuri Şahin", hint: "یاریزانی نێودەوڵەتیی تورکیا بە ڕەچەڵەک کورد؛ گەنجترین یاریزانی مێژووی بوندسلیگا؛ پاڵەوانی ٢٠١ لەگەڵ دۆرتموند", difficulty: "easy", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Nuri_%C5%9Eahin_2019.jpg/440px-Nuri_%C5%9Eahin_2019.jpg" },
    { name: "دەنیز ناکی", latin: "Deniz Naki", hint: "یاریزانی کوردی ئەڵمانیا کە بۆ ئامەدسپۆر یاری کرد؛ لە ٢٠١٨ بەهۆی هەڵوێستە کوردییەکانی بۆ هەمیشە لە یاری قەدەغە کرا؛ لە ئەڵمانیا ئۆتۆمبێلەکەی تەقەی لێکرا", difficulty: "hard" },
    { name: "وریا غەفووری", latin: "Voria Ghafouri", hint: "یاریزانی کوردی ئێران لە سنە؛ کاپتنی یانەی ئیستقلال و یاریزانی تیمی نیشتمانی؛ لە تشرینی دووەمی ٢٠٢٢ بەهۆی پشتیوانی لە ناڕەزایییەکان دەستگیرکرا", difficulty: "hard" },
  ],
};
